"""H3: every payload fixture through its lib, byte-diffed against expected.

Classifier inputs only: no command string in a fixture is ever executed.
Fixture groups map to libs by directory; the name prefix states the verdict
the fixture must produce (bypass-/deny- a deny, advise- an advisory, allow-
silence), so a fixture that drifts to the wrong verdict fails even when its
expected file is regenerated by mistake.
"""
import json
import os
import re
import sys
import unittest
from pathlib import Path

TESTS = Path(__file__).resolve().parent
FIXTURES = TESTS / "fixtures"
EXPECTED = TESTS / "expected"
sys.path.insert(0, str(TESTS.parent / "lib"))

import dangerous_ops_guard  # noqa: E402
import dispatch  # noqa: E402
import frontmatter_guard  # noqa: E402
import openpyxl_guard  # noqa: E402
import read_deny  # noqa: E402

# Every fixture's expected verdict is written against the template's shipped
# structure (main-only git mode, default lanes). The libs under test default
# to load_structure(), which reads whatever structure.json the checkout the
# suite runs from actually ships; on an adopted host that can be "branches"
# mode or null lanes. HARNESS_STRUCTURE_FILE pins the loader to the fixed
# template default for the life of this module so fixture bytes stay
# deterministic on any host (test-only override, see hook_io's docstring).
_STRUCTURE_OVERRIDE = str((TESTS.parents[2] / "harness" / "tools" / "templates" / "structure.default.json").resolve())
_PRIOR_STRUCTURE_ENV = None


def setUpModule():
    global _PRIOR_STRUCTURE_ENV
    _PRIOR_STRUCTURE_ENV = os.environ.get("HARNESS_STRUCTURE_FILE")
    os.environ["HARNESS_STRUCTURE_FILE"] = _STRUCTURE_OVERRIDE


def tearDownModule():
    if _PRIOR_STRUCTURE_ENV is None:
        os.environ.pop("HARNESS_STRUCTURE_FILE", None)
    else:
        os.environ["HARNESS_STRUCTURE_FILE"] = _PRIOR_STRUCTURE_ENV

MIN_GUARD_FIXTURES = 27
DENY_KEYS = {"hookEventName", "permissionDecision", "permissionDecisionReason"}
# <hook-name> [<tier>]: <reason>. [command-sha256:<hex>] <recovery sentence>
REASON_SHAPE = re.compile(r"^[a-z][a-z-]* \[[a-z][a-z-]*\]: .+\. \[command-sha256:[0-9a-f]{64}\] \S.*$", re.DOTALL)

# Bypass classes SECURITY.md names; each must have a guard fixture.
REQUIRED_GUARD_CLASSES = [
    "bypass-force-push-main",
    "bypass-force-push-head-refspec",
    "bypass-plus-refspec",
    "bypass-git-c-force-push",
    "bypass-rm-split-flags",
    "bypass-rm-long-flags",
    "bypass-rm-root",
    "bypass-rm-root-glob",
    "bypass-rm-home-tilde",
    "bypass-rm-home-var",
    "bypass-powershell-drive-root",
    "bypass-chmod-recursive-000",
    "bypass-chown-system-path",
    "bypass-git-filter-repo",
    "bypass-git-filter-branch",
    "bypass-git-reset-hard-main",
    "bypass-git-branch-force-delete-main",
    "allow-benign-compound",
    "allow-push-feature-branch",
    "bypass-sql-client-drop",
    "bypass-sql-drop-statement",
    "allow-sql-grep-mention",
    "allow-sql-commit-message",
    "allow-sql-echo-words",
    "bypass-cat-env",
    "bypass-get-content-pem",
    "allow-env-prose-mention",
    "allow-grep-pattern-file",
    "allow-echo-token-variable",
    "allow-heredoc-safe-sink",
    "bypass-heredoc-interpreter",
    "bypass-redirect-read",
    "bypass-bash-c-string-reader",
    "bypass-quoted-assignment-prefix",
    "bypass-sudo-user-reader",
    "bypass-git-global-option-bare-force",
    "bypass-quoted-force-flag",
    "bypass-quoted-delete-refspec",
    "bypass-lease-with-delete",
    "bypass-dry-run-cancelled",
    "bypass-rm-flags-after-operand",
    "bypass-powershell-literalpath-colon",
    "bypass-cat-windows-aws-credentials",
    "bypass-apostrophe-prose-then-rm-root",
    "allow-single-quoted-git-prose",
    "allow-refspec-dest-feature",
    "allow-git-push-bare",
    "bypass-comment-then-newline-reader",
    "bypass-process-substitution-read",
    "bypass-reserved-word-then-reader",
    "bypass-ansi-c-quoted-reader",
    "bypass-powershell-array-reader",
    "bypass-rm-dot-component",
    "bypass-short-dry-run-cancelled",
    "allow-commit-message-open-call",
    "allow-python-open-write-mode",
    "allow-shell-c-positional-argument",
]


def run_group(group, name, payload):
    if group == "guard":
        return dangerous_ops_guard.decide(payload)
    if group == "openpyxl":
        return openpyxl_guard.decide(payload)
    if group == "frontmatter":
        return frontmatter_guard.decide(payload)
    if group == "read-deny":
        environ = {} if name.endswith("-flag-off") else {"HARNESS_READ_DENY": "1"}
        return read_deny.decide(payload, environ)
    raise AssertionError("unknown fixture group " + group)


def expected_verdict(name):
    prefix = name.split("-", 1)[0]
    return {"bypass": "deny", "deny": "deny", "advise": "advisory", "allow": "silence"}[prefix]


def fixtures():
    for path in sorted(FIXTURES.glob("*/*.json")):
        yield path.parent.name, path.stem, path


class FixtureRegressions(unittest.TestCase):
    def test_at_least_the_required_number_of_guard_fixtures(self):
        names = {path.stem for path in (FIXTURES / "guard").glob("*.json")}
        assert len(names) >= MIN_GUARD_FIXTURES, len(names)
        missing = [name for name in REQUIRED_GUARD_CLASSES if name not in names]
        assert not missing, missing

    def test_every_fixture_has_an_expected_file_and_vice_versa(self):
        fixture_keys = {(group, name) for group, name, _ in fixtures()}
        expected_keys = {(path.parent.name, path.stem) for path in EXPECTED.glob("*/*.expected")}
        assert fixture_keys == expected_keys, fixture_keys ^ expected_keys

    def test_every_fixture_matches_its_expected_bytes(self):
        for group, name, path in fixtures():
            with self.subTest(group=group, name=name):
                payload = json.loads(path.read_text(encoding="utf-8"))
                out = run_group(group, name, payload)
                actual = ((out + "\n") if out else "").encode("utf-8")
                expected = (EXPECTED / group / (name + ".expected")).read_bytes()
                assert actual == expected

    def test_every_fixture_produces_the_verdict_its_name_states(self):
        for group, name, path in fixtures():
            with self.subTest(group=group, name=name):
                payload = json.loads(path.read_text(encoding="utf-8"))
                out = run_group(group, name, payload)
                verdict = expected_verdict(name)
                if verdict == "silence":
                    assert out is None
                    continue
                assert out is not None
                value = json.loads(out)
                if verdict == "deny":
                    assert set(value) == {"hookSpecificOutput"}
                    specific = value["hookSpecificOutput"]
                    assert set(specific) == DENY_KEYS
                    assert specific["hookEventName"] == "PreToolUse"
                    assert specific["permissionDecision"] == "deny"
                    reason = specific["permissionDecisionReason"]
                    assert REASON_SHAPE.match(reason), reason
                else:
                    assert "permissionDecision" not in json.dumps(value)
                    assert set(value) in ({"systemMessage"}, {"hookSpecificOutput"})

    def test_guard_fixtures_agree_with_the_dispatcher(self):
        for group, name, path in fixtures():
            if group not in ("guard", "openpyxl"):
                continue
            with self.subTest(name=name):
                result = dispatch.dispatch("PreToolUse", path.read_text(encoding="utf-8"), runtime="codex")
                denied = bool(result and result["hookSpecificOutput"].get("permissionDecision") == "deny")
                assert denied == (expected_verdict(name) == "deny")

    def test_fixture_payloads_carry_the_envelope_fields(self):
        for group, name, path in fixtures():
            with self.subTest(name=name):
                payload = json.loads(path.read_text(encoding="utf-8"))
                assert payload["hook_event_name"] in ("PreToolUse", "PostToolUse")
                assert isinstance(payload["tool_name"], str)
                assert isinstance(payload["tool_input"], dict)


class GuardBehaviorTests(unittest.TestCase):
    def denied(self, command):
        return dangerous_ops_guard.classify(dangerous_ops_guard.strip_safe_contexts(command))[0]

    def test_sql_prose_versus_execution_context(self):
        assert not self.denied('grep -rn "drop table" migrations/')
        assert not self.denied("echo drop table sessions")
        assert self.denied("echo 'drop table sessions;'")
        assert self.denied("sqlite3 app.db 'drop table sessions'")

    def test_credential_read_requires_reader_plus_path_argument(self):
        assert self.denied("cat " + ".env")
        assert self.denied("sudo cat " + ".env")
        assert self.denied("type " + ".env")
        assert not self.denied("cat " + ".env.template")
        assert not self.denied("ls -la " + ".env")
        assert not self.denied("echo $SECRET_TOKEN")

    def test_secret_path_set_includes_structure_outbound_globs(self):
        structure = {"outbound_globs": ["docs/private/**"]}
        assert dangerous_ops_guard.reads_secret("cat docs/private/notes.md", structure)
        assert not dangerous_ops_guard.reads_secret("cat docs/public/notes.md", structure)
        assert not dangerous_ops_guard.reads_secret("cat docs/private/notes.md", {"outbound_globs": []})

    def test_command_digest_is_over_the_raw_command(self):
        import hashlib
        command = "rm -rf /"
        out = dangerous_ops_guard.decide({"tool_name": "Bash", "tool_input": {"command": command}})
        digest = hashlib.sha256(command.encode("utf-8")).hexdigest()
        assert "[command-sha256:%s]" % digest in out

    def test_bare_force_push_is_protected_only_in_main_only_mode(self):
        # Fixture payloads cannot carry a custom structure.json, so the
        # branches-mode allow for a bare force push is covered here instead.
        main_only = {"git": {"mode": "main-only"}}
        branches = {"git": {"mode": "branches"}}
        assert dangerous_ops_guard.classify("git push -f", main_only)[0]
        assert dangerous_ops_guard.classify("git push -f origin", main_only)[0]
        assert not dangerous_ops_guard.classify("git push -f", branches)[0]
        assert not dangerous_ops_guard.classify("git push -f origin", branches)[0]
        # An explicit refspec is never "bare", regardless of mode.
        assert not dangerous_ops_guard.classify("git push -f origin feature", main_only)[0]

    def test_force_with_all_refs_is_protected_in_either_git_mode(self):
        branches = {"git": {"mode": "branches"}}
        assert dangerous_ops_guard.classify("git push --force --all origin", branches)[0]
        assert not dangerous_ops_guard.classify("git push --force origin feature", branches)[0]

    def test_a_refspec_is_classified_by_its_destination_side(self):
        assert not self.denied("git push --force origin main:feature")
        assert self.denied("git push --force origin feature:main")
        assert self.denied("git push --force origin HEAD~1:main")
        assert not self.denied("git push --force origin HEAD:feature")

    def test_a_lease_allows_a_push_but_never_a_protected_deletion(self):
        assert not self.denied("git push --force-with-lease origin main")
        assert self.denied("git push --force-with-lease origin :main")

    def test_an_unquoted_comment_is_not_an_argument(self):
        assert self.denied("git push --force origin main # --dry-run")
        assert not self.denied("git push --force origin main --dry-run # deploy")

    def test_single_quoted_text_is_inert_unless_a_shell_runs_the_string(self):
        assert not self.denied("echo 'git push --force origin main'")
        assert self.denied("bash -c 'git push --force origin main'")

    def test_delete_flags_and_operands_parse_in_any_order(self):
        assert self.denied("rm ../victim -rf")
        assert not self.denied("rm ../notes.txt -f")
        assert not self.denied("rm -rf ./build/../dist")

    def test_cancellation_is_symmetric_across_option_spellings(self):
        assert not self.denied("git push -f --no-force origin main")
        assert not self.denied("git push --force --no-force origin main")
        assert self.denied("git push -n --no-dry-run -f origin main")
        assert self.denied("git push --dry-run --no-dry-run -f origin main")

    def test_an_interpreter_call_is_a_read_but_prose_is_not(self):
        assert self.denied("""python -c "print(open('.env').read())" """)
        assert not self.denied("""python -c "open('.env', 'w').write('X=1')" """)
        assert not self.denied("""git commit -m "docs: open('.env') stays closed" """)

    def test_a_reserved_word_never_hides_the_command(self):
        assert self.denied("if true; then cat .env; fi")
        assert self.denied("while true; do cat .env; break; done")
        assert self.denied("builtin cat .env")

    def test_process_substitution_body_is_a_command(self):
        assert self.denied("cat <(cat .env)")
        assert self.denied("cat > >(cat .env)")
        assert not self.denied("cat <(cat README.md)")

    def test_a_comment_hides_nothing_after_the_line_break(self):
        assert self.denied("echo ok # explain" + chr(10) + "cat .env")
        assert not self.denied("echo ok # cat .env")


if __name__ == "__main__":
    unittest.main()
