#!/usr/bin/env python3
"""gen_manifest.py - generated views of the skill catalog and routing policy.

Scans every harness/skills/<name>/SKILL.md (and _vendor/<source>/<name>/SKILL.md),
reads the frontmatter, and writes:

    harness/skills/RESOLVER.md            one row per metadata.triggers phrase
    harness/registry/skill-index.json     machine-readable catalog (generated, untracked cache;
                                          --check tolerates its absence, never a stale copy)
    THIRD-PARTY.md                         one table row per harness/registry/sources.json entry

and refreshes the three generated routing views inside harness/rules/base-routing.md
(<!-- gen:routing-tasks -->, routing-profiles, routing-tools) when those markers exist.

Usage:
    python harness/tools/gen_manifest.py            # regenerate
    python harness/tools/gen_manifest.py --check    # exit 1 if anything would change
    python harness/tools/gen_manifest.py --licenses # print a tab-separated sources.json dump
                                                     # (for the scaffold's NOTICE; THIRD-PARTY.md
                                                     # itself is written by the default run above)

Marker syntax in docs:  <!-- gen:BLOCK-ID --> ... <!-- /gen:BLOCK-ID -->
Everything between the markers is machine-owned; do not hand-edit.

The skill count block in harness/CONTRACT.md is never written by this tool
(the contract is hand-authored); the lint compares the contract to
skill-index.json instead. Zero skills is a valid state: the resolver is then an
empty table with its header.
"""

from __future__ import annotations

# A sibling module in this directory shares its name with the standard
# library's select module, and a script's own directory heads sys.path. Keep
# this directory at the tail of sys.path so the stdlib wins for "import select"
# while sibling modules still resolve, and pin the stdlib module before any
# later import (subprocess on POSIX needs it) can be shadowed.
import os as _os
import sys as _sys

_TOOLS_DIR = _os.path.dirname(_os.path.abspath(__file__))
_sys.path[:] = [entry for entry in _sys.path if _os.path.abspath(entry or _os.curdir) != _TOOLS_DIR]
_sys.path.append(_TOOLS_DIR)
import selectors as _selectors  # noqa: E402,F401  (imports the stdlib select module)

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import routing_policy as rp  # noqa: E402


ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIR = Path("harness/skills")
RESOLVER = Path("harness/skills/RESOLVER.md")
SKILL_INDEX = Path("harness/registry/skill-index.json")
SOURCES = Path("harness/registry/sources.json")
THIRD_PARTY = Path("THIRD-PARTY.md")
VENDOR_DIR = "_vendor"
# Generated caches that are never tracked: absence is not drift, only a
# present-and-different copy is. RESOLVER.md is tracked and always compared.
UNTRACKED_OUTPUTS = {SKILL_INDEX}

VALID_STATUSES = ("implemented", "spec-only", "stub")
VALID_DISTRIBUTIONS = ("native", "vendored", "runtime-provided")
VALID_LICENSES = ("MIT", "Apache-2.0", "BSD-3-Clause", "source-available", "none")
KEBAB = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

ROUTING_BLOCKS = {
    "routing-tasks": rp.render_task_table,
    "routing-profiles": rp.render_profile_table,
    "routing-tools": rp.render_tool_table,
}
RESOLVER_COLUMNS = ("Intent phrase", "Target skill", "Neighbor", "Pack", "Status")
RESOLVER_HEADER = (
    "<!-- GENERATED by harness/tools/gen_manifest.py from each skill's metadata.triggers. "
    "Do not edit by hand; edit the skill's frontmatter and regenerate. -->\n"
    "\n"
    "# Skill resolver\n"
    "\n"
    "Routes an intent to the skill that owns it. One row per trigger phrase; `Target skill` is the "
    "skill to use, `Neighbor` is the skill named in the target's `WHEN NOT` clause: where an adjacent "
    "intent goes when it is not the target's job (`none` when the clause names no skill). The column is "
    "a routing boundary, not a fallback: when a target is deselected or its runtime-provided capability "
    "is absent, the skill body and the capability's `unready_behavior` in "
    "`harness/registry/capabilities.json` govern. Generated from `metadata.triggers` (`metadata.neighbor` "
    "overrides the derived neighbor); `python harness/tools/resolver_lint.py` checks that every target "
    "exists and notes every target outside the effective selection.\n"
    "\n"
)


# ---------------------------------------------------------------------------
# Frontmatter (a deliberately small YAML subset: scalars, block scalars,
# nested mappings by indentation, inline and block lists, quotes, null/bools)
# ---------------------------------------------------------------------------

def _scalar(raw: str) -> Any:
    value = raw.strip()
    if value == "" or value in {"null", "~"}:
        return None
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        inner = value[1:-1]
        return inner.replace('\\"', '"') if value[0] == '"' else inner
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_scalar(item) for item in _split_inline_list(inner)]
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


def _split_inline_list(inner: str) -> list[str]:
    items, current, quote = [], [], None
    for character in inner:
        if quote:
            current.append(character)
            if character == quote:
                quote = None
        elif character in "\"'":
            quote = character
            current.append(character)
        elif character == ",":
            items.append("".join(current))
            current = []
        else:
            current.append(character)
    if current or items:
        items.append("".join(current))
    return [item for item in items if item.strip()]


def _strip_comment(line: str) -> str:
    quote = None
    for index, character in enumerate(line):
        if quote:
            if character == quote:
                quote = None
        elif character in "\"'":
            quote = character
        elif character == "#" and (index == 0 or line[index - 1] in " \t"):
            return line[:index].rstrip()
    return line.rstrip()


def parse_yaml_block(lines: list[str]) -> Any:
    """Parse a mapping or list from indented lines. Returns dict, list, or scalar."""
    cleaned = [(line, _strip_comment(line)) for line in lines]
    cleaned = [(raw, text) for raw, text in cleaned if text.strip()]
    if not cleaned:
        return {}
    indent = min(len(text) - len(text.lstrip(" ")) for _, text in cleaned)
    entries = [(raw, text[indent:]) for raw, text in cleaned]
    if all(text.startswith("- ") or text == "-" for _, text in entries):
        return _parse_list(entries)
    return _parse_mapping(entries)


def _child_lines(entries: list[tuple[str, str]], start: int) -> tuple[list[str], int]:
    children = []
    index = start
    while index < len(entries):
        text = entries[index][1]
        if text.startswith(" "):
            children.append(text)
            index += 1
        else:
            break
    return children, index


def _parse_list(entries: list[tuple[str, str]]) -> list[Any]:
    values: list[Any] = []
    index = 0
    while index < len(entries):
        text = entries[index][1]
        body = text[2:] if text.startswith("- ") else ""
        children, index = _child_lines(entries, index + 1)
        if body and ":" in body and not body.lstrip().startswith(("\"", "'", "[")) and re.match(r"^[\w.-]+:\s", body + " "):
            nested = [body] + [child[2:] if child.startswith("  ") else child.lstrip() for child in children]
            values.append(parse_yaml_block(nested))
        elif children:
            values.append(parse_yaml_block(children))
        else:
            values.append(_scalar(body))
    return values


def _parse_mapping(entries: list[tuple[str, str]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    index = 0
    while index < len(entries):
        text = entries[index][1]
        match = re.match(r"^([\w.-]+):(.*)$", text)
        if not match:
            index += 1
            continue
        key, rest = match.group(1), match.group(2).strip()
        children, index = _child_lines(entries, index + 1)
        if rest in {">", "|", ">-", "|-"}:
            folded = rest.startswith(">")
            parts = [child.strip() for child in children]
            result[key] = (" ".join(parts) if folded else "\n".join(parts)).strip()
        elif rest == "":
            result[key] = parse_yaml_block(children) if children else None
        else:
            result[key] = _scalar(rest)
    return result


def parse_frontmatter(text: str) -> dict[str, Any] | None:
    """Return the frontmatter mapping, or None when the file has no block."""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    try:
        closing = next(index for index, line in enumerate(lines[1:], 1) if line.strip() == "---")
    except StopIteration:
        return None
    value = parse_yaml_block(lines[1:closing])
    return value if isinstance(value, dict) else {}


# ---------------------------------------------------------------------------
# Skill catalog
# ---------------------------------------------------------------------------

@dataclass
class Skill:
    name: str
    path: str
    status: str = ""
    description: str = ""
    packs: list[str] = field(default_factory=list)
    triggers: list[str] = field(default_factory=list)
    requires: list[str] = field(default_factory=list)
    distribution: str = ""
    license: str = ""
    notice: str | None = None
    neighbor: str = "none"
    neighbor_explicit: bool = False
    frontmatter: dict[str, Any] = field(default_factory=dict)
    problems: list[str] = field(default_factory=list)
    route_owner: str = ""


def skill_files(root: Path) -> list[Path]:
    base = Path(root) / SKILLS_DIR
    if not base.is_dir():
        return []
    files = sorted(path for path in base.glob("*/SKILL.md") if not path.parent.name.startswith("_"))
    files.extend(sorted(base.glob(f"{VENDOR_DIR}/*/*/SKILL.md")))
    return files


def _string_list(value: Any, label: str, problems: list[str]) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, list) or any(not isinstance(item, str) or not item.strip() for item in value):
        problems.append(f"{label} must be a list of non-empty strings")
        return []
    return [item.strip() for item in value]


def load_skill(root: Path, skill_md: Path) -> Skill:
    relative = skill_md.parent.relative_to(Path(root)).as_posix()
    skill = Skill(name=skill_md.parent.name, path=relative)
    try:
        text = skill_md.read_text(encoding="utf-8-sig")
    except OSError as exc:
        skill.problems.append(f"unreadable: {exc}")
        return skill
    frontmatter = parse_frontmatter(text)
    if frontmatter is None:
        skill.problems.append("missing frontmatter block")
        return skill
    skill.frontmatter = frontmatter
    name = frontmatter.get("name")
    if not isinstance(name, str) or not name.strip():
        skill.problems.append("name is required")
    elif name.strip() != skill_md.parent.name:
        skill.problems.append(f"name {name.strip()!r} does not match folder {skill_md.parent.name!r}")
    description = frontmatter.get("description")
    if not isinstance(description, str) or not description.strip():
        skill.problems.append("description is required")
    else:
        skill.description = description.strip()
        if "WHEN:" not in skill.description:
            skill.problems.append("description must contain 'WHEN:'")
    metadata = frontmatter.get("metadata")
    if not isinstance(metadata, dict):
        skill.problems.append("metadata block is required")
        metadata = {}
    skill.packs = _string_list(metadata.get("packs"), "metadata.packs", skill.problems)
    if "packs" not in metadata or not skill.packs:
        skill.problems.append("metadata.packs is required and must not be empty")
    for pack in skill.packs:
        if not KEBAB.match(pack):
            skill.problems.append(f"pack slug {pack!r} is not kebab-case")
    skill.triggers = _string_list(metadata.get("triggers"), "metadata.triggers", skill.problems)
    if "triggers" not in metadata or not skill.triggers:
        skill.problems.append("metadata.triggers is required and must not be empty")
    skill.requires = _string_list(metadata.get("requires"), "metadata.requires", skill.problems)
    status = metadata.get("status")
    if status not in VALID_STATUSES:
        skill.problems.append(f"metadata.status must be one of {', '.join(VALID_STATUSES)} (got {status!r})")
    else:
        skill.status = status
    distribution = metadata.get("distribution")
    if distribution not in VALID_DISTRIBUTIONS:
        skill.problems.append(
            f"metadata.distribution must be one of {', '.join(VALID_DISTRIBUTIONS)} (got {distribution!r})"
        )
    else:
        skill.distribution = distribution
    license_value = metadata.get("license")
    if license_value not in VALID_LICENSES:
        skill.problems.append(f"metadata.license must be one of {', '.join(VALID_LICENSES)} (got {license_value!r})")
    else:
        skill.license = license_value
    notice = metadata.get("notice")
    if notice is not None and not isinstance(notice, str):
        skill.problems.append("metadata.notice must be a string or null")
    else:
        skill.notice = notice
    neighbor = metadata.get("neighbor")
    if neighbor is not None:
        if not isinstance(neighbor, str) or not neighbor.strip():
            skill.problems.append("metadata.neighbor must be a skill name, none, or absent")
        else:
            skill.neighbor = neighbor.strip()
            skill.neighbor_explicit = True
    route_owner = metadata.get("route_owner")
    if isinstance(route_owner, str):
        skill.route_owner = route_owner.strip()
    return skill


def _neighbor_from_description(skill: Skill, names: set[str]) -> str:
    """The first existing skill named in the WHEN NOT clause, else none.

    This is the routing boundary the clause draws (where an adjacent intent
    goes), never a fallback for a deselected target or an absent capability.
    """
    match = re.search(r"WHEN NOT:(.*)", skill.description, re.DOTALL)
    if not match:
        return "none"
    for candidate in re.findall(r"(?:/|`)([a-z][a-z0-9-]*)`?", match.group(1)):
        if candidate in names and candidate != skill.name:
            return candidate
    return "none"


def scan_skills(root: Path = ROOT) -> list[Skill]:
    """Every skill in the catalog, sorted by name, with per-skill problems."""
    skills = [load_skill(root, path) for path in skill_files(root)]
    names = {skill.name for skill in skills}
    for skill in skills:
        if not skill.neighbor_explicit and skill.description:
            skill.neighbor = _neighbor_from_description(skill, names)
        if skill.neighbor != "none" and skill.neighbor not in names:
            skill.problems.append(f"metadata.neighbor {skill.neighbor!r} is not a skill")
        elif skill.neighbor == skill.name:
            skill.problems.append("metadata.neighbor names the skill itself")
    return sorted(skills, key=lambda item: item.name)


def status_tally(skills: list[Skill]) -> dict[str, int]:
    tally = {status: 0 for status in VALID_STATUSES}
    for skill in skills:
        if skill.status in tally:
            tally[skill.status] += 1
    return tally


# ---------------------------------------------------------------------------
# Generated outputs
# ---------------------------------------------------------------------------

def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def resolver_rows(skills: list[Skill]) -> list[tuple[str, str, str, str, str]]:
    rows = []
    for skill in sorted(skills, key=lambda item: (sorted(item.packs)[0] if item.packs else "~", item.name)):
        pack = ", ".join(sorted(skill.packs)) or "none"
        for trigger in skill.triggers:
            rows.append((trigger, skill.name, skill.neighbor, pack, skill.status or "unknown"))
    return rows


def render_resolver(skills: list[Skill]) -> str:
    lines = [RESOLVER_HEADER.rstrip("\n"), ""]
    lines.append("| " + " | ".join(RESOLVER_COLUMNS) + " |")
    lines.append("|" + "---|" * len(RESOLVER_COLUMNS))
    for trigger, target, neighbor, pack, status in resolver_rows(skills):
        neighbor_cell = "none" if neighbor == "none" else f"`{neighbor}`"
        lines.append(f"| \"{_cell(trigger)}\" | `{target}` | {neighbor_cell} | {_cell(pack)} | {status} |")
    return "\n".join(lines) + "\n"


def render_skill_index(skills: list[Skill]) -> str:
    index = {
        "schema_version": 1,
        "total": len(skills),
        "counts": status_tally(skills),
        "skills": [
            {
                "name": skill.name,
                "path": skill.path,
                "packs": sorted(skill.packs),
                "status": skill.status,
                "distribution": skill.distribution,
                "license": skill.license,
                "requires": skill.requires,
                "triggers": skill.triggers,
                "neighbor": skill.neighbor,
            }
            for skill in skills
        ],
    }
    return json.dumps(index, indent=2, sort_keys=True) + "\n"


def write_lf(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    temporary.replace(path)


def replace_block(text: str, block_id: str, content: str) -> str | None:
    pattern = re.compile(
        rf"(<!-- gen:{re.escape(block_id)} -->)(.*?)(<!-- /gen:{re.escape(block_id)} -->)",
        re.DOTALL,
    )
    if not pattern.search(text):
        return None
    return pattern.sub(lambda match: f"{match.group(1)}\n{content}\n{match.group(3)}", text)


def gen_routing_views(root: Path, check: bool) -> tuple[list[str], list[str], list[str]]:
    """Refresh the generated tables inside base-routing.md. Returns (drift, problems, notes)."""
    drift: list[str] = []
    notes: list[str] = []
    source_path = Path(root) / rp.SOURCE
    if not source_path.is_file():
        notes.append(f"{rp.SOURCE.as_posix()} absent; routing views skipped")
        return drift, [], notes
    try:
        policy = rp.load_policy(root)
    except rp.PolicyError as exc:
        return drift, [f"routing-policy: {exc}"], notes
    source = source_path.read_text(encoding="utf-8-sig")
    updated = source
    for block_id, renderer in ROUTING_BLOCKS.items():
        next_text = replace_block(updated, block_id, renderer(policy))
        if next_text is None:
            notes.append(f"{rp.SOURCE.as_posix()}: markers for '{block_id}' not found; view not written")
        else:
            updated = next_text
    if updated != source:
        drift.append(f"{rp.SOURCE.as_posix()} [routing-views]")
        if not check:
            write_lf(source_path, updated)
    return drift, [], notes


def generate(root: Path = ROOT, check: bool = False) -> tuple[list[str], list[str], list[str]]:
    """Write (or, with check, compare) every generated view. Returns (drift, problems, notes)."""
    root = Path(root)
    skills = scan_skills(root)
    problems = [f"{skill.path}: {problem}" for skill in skills for problem in skill.problems]
    drift: list[str] = []
    notes: list[str] = []
    if not (root / SKILLS_DIR).is_dir():
        notes.append(f"{SKILLS_DIR.as_posix()} absent; resolver rendered empty")

    outputs = {
        RESOLVER: render_resolver(skills),
        SKILL_INDEX: render_skill_index(skills),
        THIRD_PARTY: render_third_party(root),
    }
    for relative, want in outputs.items():
        target = root / relative
        have = target.read_text(encoding="utf-8-sig") if target.is_file() else None
        if have == want:
            continue
        if have is None and relative in UNTRACKED_OUTPUTS and check:
            notes.append(f"{relative.as_posix()} absent (untracked cache); run without --check to write it")
            continue
        drift.append(relative.as_posix() + ("" if have is not None else " (missing)"))
        if not check:
            write_lf(target, want)

    view_drift, view_problems, view_notes = gen_routing_views(root, check)
    drift.extend(view_drift)
    problems.extend(view_problems)
    notes.extend(view_notes)
    return drift, problems, notes


def _third_party_cell(value: str) -> str:
    """Escape a literal pipe so a stray one in a notice or URL cannot break the table row."""
    return value.replace("|", "\\|")


def render_third_party(root: Path = ROOT) -> str:
    """THIRD-PARTY.md body: one table row per harness/registry/sources.json entry.

    Kept in its own renderer (rather than reusing render_licenses' tab-separated
    form) because the two outputs serve different readers: render_licenses is a
    machine-oriented dump for the scaffold's NOTICE, this is the Markdown table
    THIRD-PARTY.md ships with, header prose and all.
    """
    path = Path(root) / SOURCES
    sources: dict[str, Any] = {}
    if path.is_file():
        try:
            registry = json.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            registry = {}
        sources = registry.get("sources", {}) if isinstance(registry, dict) else {}
    rows = []
    for source_id in sorted(sources):
        entry = sources[source_id] if isinstance(sources[source_id], dict) else {}
        assets = entry.get("assets", [])
        assets_cell = ", ".join(str(item) for item in assets) if isinstance(assets, list) else ""
        cells = (
            f"`{source_id}`",
            str(entry.get("origin", "")),
            str(entry.get("license", "")),
            "modified" if entry.get("modified") else "unmodified",
            str(entry.get("notice") or ""),
            assets_cell,
        )
        # An empty cell renders as a single bare space between its bordering
        # pipes (matching the hand-authored table this replaces), not a
        # padded-then-doubled space, so "| |" and never "|  |".
        padded = [f" {_third_party_cell(cell)} " if cell else " " for cell in cells]
        rows.append("|" + "|".join(padded) + "|")
    lines = [
        "<!-- GENERATED by harness/tools/gen_manifest.py from harness/registry/sources.json. "
        "Do not edit by hand; edit sources.json and regenerate. -->",
        "",
        "# Third-party notices",
        "",
        "Every vendored or adapted asset in this repository is listed here with its origin, license, "
        "and modification status. The table is regenerated from `harness/registry/sources.json`; "
        "`python harness/tools/gen_manifest.py --check` fails when the two disagree.",
        "",
        "| Source | Origin | License | Modified | Notice | Assets |",
        "|---|---|---|---|---|---|",
    ]
    lines.extend(rows)
    return "\n".join(lines) + "\n"


def render_licenses(root: Path = ROOT) -> str:
    """One line per sources.json entry, for the scaffold's NOTICE and THIRD-PARTY.md."""
    path = Path(root) / SOURCES
    lines = ["# id\torigin\tlicense\tmodified\tassets\tnotice"]
    if not path.is_file():
        return "\n".join(lines) + "\n"
    registry = json.loads(path.read_text(encoding="utf-8-sig"))
    sources = registry.get("sources", {}) if isinstance(registry, dict) else {}
    for source_id in sorted(sources):
        entry = sources[source_id] if isinstance(sources[source_id], dict) else {}
        assets = entry.get("assets", [])
        lines.append("\t".join([
            source_id,
            str(entry.get("origin", "")),
            str(entry.get("license", "")),
            "modified" if entry.get("modified") else "unmodified",
            ", ".join(assets) if isinstance(assets, list) else "",
            str(entry.get("notice") or ""),
        ]))
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the skill resolver, skill index, THIRD-PARTY.md, and routing views.")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true", help="exit 1 if any generated file would change")
    parser.add_argument("--licenses", action="store_true", help="print license lines from sources.json and exit")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.licenses:
        sys.stdout.write(render_licenses(root))
        return 0
    drift, problems, notes = generate(root, check=args.check)
    for note in notes:
        print(f"NOTE     {note}")
    for problem in problems:
        print(f"PROBLEM  {problem}")
    for item in drift:
        print(f"{'DRIFT' if args.check else 'UPDATED'}  {item}")
    if not drift and not problems:
        print("OK  resolver, skill index, THIRD-PARTY.md, and routing views in sync")
    return 1 if (args.check and drift) or problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
