#!/usr/bin/env python3
"""Build or exactly check the generated OpenCode slash commands (.opencode/commands).

One ``<name>.md`` command per SELECTED, non-stub skill. Each command tells
OpenCode to load the native skill through its ``skill`` tool; it never copies
the procedure. Every generated file carries a marker comment, and the
directory carries a ``.generated-by`` file, so the prune step can tell
harness-managed commands from a user's own. Zero skills is legal.

The selected skill tree that OpenCode links as its skill root
(``harness/.selected/skills``) is produced by materialize.py, not here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import tempfile
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
from skill_catalog import SkillError, selected_skills, yaml_string  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
GENERATOR = "harness/bootstrap/build_opencode_adapter.py"
MARKER = ".generated-by"
MARKER_BYTES = (GENERATOR + "\n").encode("utf-8")
FILE_MARKER = f"<!-- generated by {GENERATOR}; do not edit -->"
DEFAULT_DESTINATION = Path(".opencode/commands")


def render_commands(root: Path) -> tuple[dict[str, bytes], list[str]]:
    """Return ({relative path: bytes}, warnings) for the selected skills."""
    skills, selected, warnings = selected_skills(Path(root))
    enabled = [skills[name] for name in selected if skills[name].status != "stub"]
    files: dict[str, bytes] = {MARKER: MARKER_BYTES}
    for skill in enabled:
        agent_header = "agent: workflow\n" if skill.name == "workflow" else ""
        files[f"{skill.name}.md"] = f"""---
description: {yaml_string(skill.description)}
{agent_header}---
{FILE_MARKER}

Use the native `skill` tool to load `{skill.name}`, read its complete
`SKILL.md`, and follow that canonical procedure for the user's arguments:

$ARGUMENTS
""".encode("utf-8")
    digest = hashlib.sha256(
        json.dumps(
            {"skills": [skills[name].public_dict() for name in selected], "selected": selected},
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()
    stats = {
        "schema_version": 1,
        "generator": GENERATOR,
        "commands": len(enabled),
        "selected": len(selected),
        "available": len(skills),
        "implemented": sum(skill.status == "implemented" for skill in enabled),
        "spec_only": sum(skill.status == "spec-only" for skill in enabled),
        "source_sha256": digest,
    }
    files[".catalog.json"] = (json.dumps(stats, indent=2) + "\n").encode("utf-8")
    return files, warnings


def is_generated_file(path: Path) -> bool:
    if not path.is_file() or path.is_symlink():
        return False
    try:
        return FILE_MARKER.encode("utf-8") in path.read_bytes()[:4096]
    except OSError:
        return False


def diff_commands(destination: Path, expected: dict[str, bytes]) -> tuple[list[str], list[str]]:
    """Return (drift problems, unmanaged notes). Read-only."""
    destination = Path(destination)
    if not destination.is_dir():
        return [f"{destination.as_posix()}: commands missing"], []
    problems: list[str] = []
    notes: list[str] = []
    for relative, content in sorted(expected.items()):
        path = destination / relative
        if not path.is_file():
            problems.append(f"{relative}: missing")
        elif path.read_bytes() != content:
            problems.append(f"{relative}: byte drift")
    for entry in sorted(destination.iterdir()):
        if entry.name in expected:
            continue
        if is_generated_file(entry):
            problems.append(f"{entry.name}: stale generated command (not selected); run bootstrap")
        else:
            notes.append(f"{entry.name}: unmanaged, left in place")
    return problems, notes


def _write_atomic(target: Path, content: bytes) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(prefix=".tmp-", dir=target.parent)
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(content)
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write_commands(root: Path, destination: Path) -> tuple[dict, list[str]]:
    """Write the commands for root into destination; return (stats, notes)."""
    files, warnings = render_commands(root)
    destination = Path(destination)
    if destination.is_symlink():
        raise RuntimeError(f"refusing to write through a link at {destination.as_posix()}")
    destination.mkdir(parents=True, exist_ok=True)
    notes = list(warnings)
    for relative, content in files.items():
        target = destination / relative
        if target.exists() and not target.is_file():
            raise RuntimeError(f"refusing to replace non-file entry {target.as_posix()}")
        if target.is_file() and target.read_bytes() == content:
            continue
        _write_atomic(target, content)
    for entry in sorted(destination.iterdir()):
        if entry.name in files:
            continue
        if is_generated_file(entry):
            entry.unlink()
            notes.append(f"pruned {entry.name}")
        else:
            notes.append(f"{entry.name}: unmanaged, left in place")
    return json.loads(files[".catalog.json"]), notes


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    parser.add_argument("--output", type=Path, help="commands directory (default .opencode/commands)")
    parser.add_argument("--check", action="store_true", help="compare exact bytes and file set; write nothing")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    destination = (args.output or (root / DEFAULT_DESTINATION)).absolute()
    try:
        if args.check:
            files, warnings = render_commands(root)
            problems, notes = diff_commands(destination, files)
            for note in warnings + notes:
                print(f"  NOTE {note}")
            if problems:
                print(f"OpenCode command catalog: {len(problems)} drift item(s)", file=sys.stderr)
                for problem in problems:
                    print(f"  DRIFT {problem}", file=sys.stderr)
                return 1
            stats = json.loads(files[".catalog.json"])
            print(
                f"OpenCode command catalog: exact ({stats['commands']} commands; "
                f"{stats['selected']} selected of {stats['available']} available)"
            )
            return 0
        stats, notes = write_commands(root, destination)
    except (KeyError, json.JSONDecodeError, OSError, RuntimeError, SkillError) as exc:
        print(f"ERROR: OpenCode command catalog: {exc}", file=sys.stderr)
        return 1
    for note in notes:
        print(f"  NOTE {note}")
    print(
        f"OpenCode command catalog: {stats['commands']} commands written to {destination.as_posix()} "
        f"({stats['selected']} selected of {stats['available']} available)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
